module.exports.BurnableERC20 = require('../solidity/compiled/BurnableERC20.json')
module.exports.BurnableMintableERC20 = require('../solidity/compiled/BurnableMintableERC20.json')
module.exports.MintableERC20 = require('../solidity/compiled/MintableERC20.json')
module.exports.StandardCrowdsale = require('../solidity/compiled/StandardCrowdsale.json')
module.exports.StandardERC20 = require('../solidity/compiled/StandardERC20.json')
